export const ActionTypes = {
    SET_FETCH_ERROR: "SET_FETCH_ERROR",

    SET_USERS: "SET_USERS", 
    SET_PROFILE: "SET_PROFILE", 
    SET_SELECTED_USER: "SET_SELECTED_USER", 

    SET_PRODUCT_CATEGORY: "SET_PRODUCT_CATEGORY",
    SET_SELECTED_CATEGORY:'SET_SELECTED_CATEGORY',
    SET_PRODUCT_SIZES: "SET_PRODUCT_SIZES",

    SET_PRODUCTS: "SET_PRODUCTS",
    SET_CREATE_PRODUCT: "SET_CREATE_PRODUCT",
    SET_SELECTED_PRODUCT: "SET_SELECTED_PRODUCT",
 

    SET_CART: "SET_CART",
    UPDATE_CART: "UPDATE_CART",
    DELETE_CARTITEM : "DELETE_CARTITEM",  
    SET_SELECTED_ORDER : "SET_SELECTED_ORDER",  
    SET_ORDER: "SET_ORDER",


    SET_PAYMENTS: "SET_PAYMENTS",
    SET_SELECTED_PAYMENTS: "SET_SELECTED_PAYMENTS",
 

}